WITH JOCURICUGENERALI AS (
    SELECT DISTINCT JO.ID_JOC
    FROM JOACA JO
    JOIN SELECTIE_CARACTER SC ON JO.NUME_UTILIZATOR = SC.NUME_UTILIZATOR
    JOIN CARACTER C ON SC.NUME_CARACTER = C.NUME_CARACTER
    JOIN ORAS O ON JO.NUME_UTILIZATOR = O.NUME_UTILIZATOR
    JOIN CLADIRE CL ON O.ID_ORAS = CL.ID_ORAS
    WHERE C.NUMAR = 8  
    AND CL.POATE_FI_AFECTATA = 1
),

JUCATORIPROTEJATI AS (
    SELECT DISTINCT NUME_UTILIZATOR
    FROM (
        SELECT SC.NUME_UTILIZATOR
        FROM SELECTIE_CARACTER SC
        JOIN CARACTER C ON SC.NUME_CARACTER = C.NUME_CARACTER
        WHERE C.NUMAR = 5
        
        UNION
        
        SELECT O.NUME_UTILIZATOR
        FROM ORAS O
        JOIN CLADIRE CL ON O.ID_ORAS = CL.ID_ORAS
        JOIN CARTE_UNICA CU ON CL.ID_CARTE = CU.ID_CARTE_UNICA
        WHERE CU.ABILITATE = 5
    )
), 

PARTICIPANTIVULNERABILI AS (
    SELECT JO.ID_JOC, JO.NUME_UTILIZATOR
    FROM JOACA JO
    JOIN JOCURICUGENERALI JG ON JO.ID_JOC = JG.ID_JOC
    WHERE NOT EXISTS (
        SELECT 1
        FROM SELECTIE_CARACTER SC
        JOIN CARACTER C ON SC.NUME_CARACTER = C.NUME_CARACTER
        WHERE SC.NUME_UTILIZATOR = JO.NUME_UTILIZATOR
        AND C.NUMAR = 8
    )
    AND NOT EXISTS (
        SELECT 1
        FROM JUCATORIPROTEJATI JP
        WHERE JP.NUME_UTILIZATOR = JO.NUME_UTILIZATOR
    )
) 
SELECT * FROM PARTICIPANTIVULNERABILI;


SELECT 
    PV.NUME_UTILIZATOR AS JUCATOR_AFECTAT,
    CL.ID_CLADIRE AS CLADIRE_DE_STERS,
    CL.POATE_FI_AFECTATA
FROM CLADIRE CL
JOIN ORAS O ON CL.ID_ORAS = O.ID_ORAS
JOIN PARTICIPANTIVULNERABILI PV ON O.NUME_UTILIZATOR = PV.NUME_UTILIZATOR
WHERE CL.POATE_FI_AFECTATA = 1
AND ROWNUM <= 10;
