--1.1
SELECT A.NUME, COUNT(DISTINCT C.ID_ARTIST_DESCHIDERE)
FROM ARTISTI A
LEFT JOIN TURNEE T ON T.ID_ARTIST = A.ID_ARTIST
LEFT JOIN CONCERTE C ON C.ID_TURNEU = T.ID_TURNEU
LEFT JOIN ARTISTI D ON D.ID_ARTIST = C.ID_ARTIST_DESCHIDERE
    AND D.TIP = 'FORMATIE' 
GROUP BY A.NUME;
--1.2
SELECT A.NUME, COUNT(DISTINCT ID_ALBUM) 
FROM ARTISTI A
LEFT JOIN ALBUME ALB ON A.ID_ARTIST = ALB.ID_ARTIST
    AND ALB.AN_LANSARE < (
         SELECT MAX(AN_DECERNARE)
         FROM PREMII_CASTIGATE PC
         WHERE PC.ID_ARTIST = A.ID_ARTIST
       )
LEFT JOIN PREMII_CASTIGATE P ON P.ID_ARTIST = A.ID_ARTIST
LEFT JOIN TURNEE T ON T.ID_ARTIST = A.ID_ARTIST
LEFT JOIN CONCERTE C ON T.ID_TURNEU = C.ID_TURNEU
    AND TO_CHAR(C.DATA, 'YYYY') = '2024'
GROUP BY A.NUME
HAVING COUNT(DISTINCT C.ID_CONCERT) >= 3;
--1.3
SELECT A.NUME AS artist, SUM(C.VENIT) 
FROM ARTISTI A
JOIN TURNEE T ON A.ID_ARTIST = T.ID_ARTIST
JOIN CONCERTE C ON T.ID_TURNEU = C.ID_TURNEU
WHERE TO_CHAR(C.DATA, 'YYYY') = 2025
AND C.ID_ARTIST_DESCHIDERE IN (
    SELECT P.ID_ARTIST
    FROM PREMII_CASTIGATE P
    GROUP BY P.ID_ARTIST
    HAVING COUNT(ID_PREMIU) >= 3
)
GROUP BY A.ID_ARTIST, A.NUME
ORDER BY SUM(C.VENIT) DESC;
