-- 2.1

SELECT P.ORAS, COUNT(DISTINCT R.id_client) 
FROM REZERVARI R
JOIN PROPRIETATI P ON R.ID_PROPRIETATE = P.ID_PROPRIETATE
WHERE R.STATUS = 'CONFIRMATA'
GROUP BY P.ORAS;

-- 2.2

SELECT DISTINCT C.ID_CLIENT, C.NUME  
FROM CLIENTI C 
JOIN REZERVARI R ON C.ID_CLIENT = R.ID_CLIENT
JOIN PLATI P ON R.ID_REZERVARE = P.ID_REZERVARE
WHERE P.METODA = 'CASH' AND 
(SELECT COUNT(ID_REVIEW)
FROM REVIEWS R2
JOIN CLIENTI C2 ON R2.ID_CLIENT = C2.ID_CLIENT
WHERE R2.RATING >= 2) >= 3;

-- 2.3

SELECT *
FROM 
(
SELECT 
    C.ID_CLIENT, C.NUME,
    SUM((R.DATA_CHECK_OUT - R.DATA_CHECK_IN) * P.PRET_PER_NOAPTE) AS TOTAL_CHELTUIELI
FROM 
    CLIENTI C
JOIN 
    REZERVARI R ON C.ID_CLIENT = R.ID_CLIENT
JOIN 
    PROPRIETATI P ON R.ID_PROPRIETATE = P.ID_PROPRIETATE
WHERE 
    TO_CHAR(R.DATA_CHECK_IN, 'YY') = 25
GROUP BY 
    C.id_client, C.NUME
ORDER BY 
    TOTAL_CHELTUIELI DESC)
WHERE ROWNUM <= (
SELECT COUNT(DISTINCT ID_PROPRIETATE)
FROM REZERVARI
WHERE TO_CHAR(DATA_CHECK_IN, 'YY') = '25');

