--CLAUZA WITH SI OPERATORUL EXISTS
--1
SELECT *
FROM EMPLOYEES E3
WHERE E3.DEPARTMENT_ID IN (
    SELECT
        DISTINCT E2.DEPARTMENT_ID
    FROM EMPLOYEES E2
    WHERE E2.SALARY = (
        SELECT
            MAX(E.SALARY)
        FROM EMPLOYEES E
        WHERE E.DEPARTMENT_ID = 30
        )
    );

SELECT *
FROM EMPLOYEES E
WHERE EXISTS(
        SELECT *
        FROM EMPLOYEES E2
        WHERE E2.SALARY = (
            SELECT
                MAX(E4.SALARY)
            FROM EMPLOYEES E4
            WHERE E4.DEPARTMENT_ID = 30) AND
              E2.DEPARTMENT_ID = E.DEPARTMENT_ID
          );

--2
WITH TABLE_SECUND AS (
    SELECT D.DEPARTMENT_NAME, SUM(E.SALARY) "SUMA TOTALA"
    FROM EMPLOYEES E
    JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    GROUP BY D.DEPARTMENT_NAME
)
SELECT *
FROM TABLE_SECUND T
WHERE T."SUMA TOTALA" > (
        SELECT AVG(T2."SUMA TOTALA")
        FROM TABLE_SECUND T2
    );

--SUBCERERI IERARHICE
--     100
--101       102
--103     104 105

--START WITH EMPLOYEE_ID = 100 -> 100LVL1, 101LVL2
--START WITH EMPLOYEE_ID = 101 -> 101LVL1, 103LVL2

--1
--A
SELECT
    E.EMPLOYEE_ID, E.MANAGER_ID, LEVEL
FROM EMPLOYEES E
WHERE LEVEL > 1
START WITH E.LAST_NAME = 'De Haan'
CONNECT BY PRIOR E.EMPLOYEE_ID = E.MANAGER_ID;

--B
SELECT
    E.EMPLOYEE_ID, E.MANAGER_ID, LEVEL
FROM EMPLOYEES E
WHERE LEVEL = 2
START WITH E.LAST_NAME = 'De Haan'
CONNECT BY PRIOR E.EMPLOYEE_ID = E.MANAGER_ID;

--C
SELECT
    E.EMPLOYEE_ID, E.MANAGER_ID, LEVEL
FROM EMPLOYEES E
WHERE LEVEL = 3
START WITH E.LAST_NAME = 'De Haan'
CONNECT BY PRIOR E.EMPLOYEE_ID = E.MANAGER_ID;

--2
SELECT
    E.EMPLOYEE_ID, E.MANAGER_ID, LEVEL
FROM EMPLOYEES E
CONNECT BY PRIOR E.MANAGER_ID = E.EMPLOYEE_ID;

--3
SELECT
    E2.EMPLOYEE_ID, (
        SELECT
            COUNT(*) - 1
        FROM EMPLOYEES E
        START WITH E.EMPLOYEE_ID = E2.EMPLOYEE_ID
        CONNECT BY PRIOR E.EMPLOYEE_ID = E.MANAGER_ID
    )
FROM EMPLOYEES E2;

--GROUP BY ROLLUP(x, y, z) -> x,y,z / x,y / x / total
--GROUP BY ROLLUP(x, y) -> x,y / x / total
--GROUP BY CUBE(x, y, z) -> x,y,z / x,y / x,z / x / y,z / y / z / total
--GROUP BY CUBE(x, y) -> x,y / y,x / x / y / total

--1.
SELECT
    D.DEPARTMENT_NAME, J.JOB_TITLE, AVG(E.SALARY),
    GROUPING(D.DEPARTMENT_NAME), GROUPING(J.JOB_TITLE)
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
GROUP BY ROLLUP(D.DEPARTMENT_NAME, J.JOB_TITLE);

--2
SELECT
    D.DEPARTMENT_NAME, J.JOB_TITLE, AVG(E.SALARY),
    CASE
        WHEN GROUPING(D.DEPARTMENT_NAME) = 1 AND GROUPING(J.JOB_TITLE) = 1 THEN 'NICIUNA'
        WHEN GROUPING(D.DEPARTMENT_NAME) = 1 AND GROUPING(J.JOB_TITLE) = 0 THEN 'JOB'
        WHEN GROUPING(D.DEPARTMENT_NAME) = 0 AND GROUPING(J.JOB_TITLE) = 1 THEN 'DEP'
        WHEN GROUPING(D.DEPARTMENT_NAME) = 0 AND GROUPING(J.JOB_TITLE) = 0 THEN 'DEPJOB'
    END
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
GROUP BY CUBE(D.DEPARTMENT_NAME, J.JOB_TITLE);

--3.
SELECT
    D.DEPARTMENT_NAME, J.JOB_TITLE, D.MANAGER_ID,
    MAX(E.SALARY), SUM(E.SALARY)
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
GROUP BY GROUPING SETS((D.DEPARTMENT_NAME, J.JOB_TITLE), (J.JOB_TITLE, D.MANAGER_ID), ());